var texCodeArray =[

    " \\frac{a}{b}",
	" \\sqrt{x}",
	" \\sqrt[n]{a}",
	" {a_n}",
	" x^n",
	" C_n^m",
	" \\overrightarrow{AB}",
	" \\widehat{AB}",
	" \\overline{x}",
	" \\sum_{k=1}^{n}f(k)",
	//" \\left\\{\\begin{matrix} x+y=a & \\\\ x-y =b & \\end{matrix}\\right.",
	" \\left\\{\\begin{matrix} x & \\\\ y  & \\end{matrix}\\right.",
	" \\lim_{k\\to\\infty}k^{-1}",	
	" \\overbrace{1+2+\\cdots+n}^{n}",
	" \\underbrace{1+2+\\cdots+n}_{n}"
	
	
	/*
	" \\infty",
	" \\pm",
	" \\leq",
	
	" \\geq",
	" \\neq",
	" \\propto",
	" \\cap",
	" \\cup",
	" \\subseteq",
	" \\supseteq",
	" \\int",
	" \\oint",
	" \\cong",
	" \\approx",
	" ≡",
	
	" ^{\\circ}",
	" ^{\\circ}F",
	" ^{\\circ}C ",
	" \\exists",
	" \\in",
	" \\ni",
	" \\neg",
	" \\forall",
	" \\Lambda",	  
	" \\alpha",
	" \\beta",
	" \\gamma",
	
	" \\delta",
	" \\varepsilon",
	" \\zeta",
	" \\eta",
	" \\theta",
	" \\vartheta ",
	" \\lambda",
	" \\Omega",
	" \\mu",
	" \\xi",
	" o",
	" \\rho",
	
	" \\varphi",
	" \\phi",
	" \\psi", 
	" \\omega",	  
	" \\angle ",
	" \\because ",
	" \\therefore ",
	" \\bot",
	" \\|",
	" \\nparallel",
	" \\odot ",	
	" \\square ",
	
	" \\bigtriangleup ",
	" \\|",
	" \\blacksquare ",
	" \\equiv",
	" \\cong",
	" \\sim ",
	  
	" \\sum_{k=1}^{n}f(k)",
	" \\lim_{k\\to\\infty}k^{-1}",
	" \\left\\{\\begin{matrix} x+y=a & \\\\ x-y =b & \\end{matrix}\\right.",
	" \\overbrace{1+2+\\cdots+n}^{n}",
	" \\underbrace{1+2+\\cdots+n}_{n}"
	*/

];